id: IA47B3ADB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T17:46:15+00:00'
last_modified: '2022-06-08T01:50:22.795782+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1088
  title: སངས་རྒྱས་སྟོང་གི་མཚན་ཟུར་དུ་བཀོལ་བ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BA98:
      image_group_id: I1CZ1469
      title: ''
      total_pages: 40
      order: 1
      base_file: BA98.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
